FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run prisma:generate
RUN npm run build

EXPOSE 4000

CMD ["sh", "-c", "npm run prisma:migrate && npm run seed:base && npm run seed:catalog && npm run start:prod"]
